// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARV_AVndT7CGUrxVrioLO7IQT_P3txjos',
    appId: '1:123921055286:web:79c0755e2bc041fdee2297',
    messagingSenderId: '123921055286',
    projectId: 'daali-mobile-project-e19fb',
    authDomain: 'daali-mobile-project-e19fb.firebaseapp.com',
    storageBucket: 'daali-mobile-project-e19fb.appspot.com',
    measurementId: 'G-TZ36BQ515W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTJNWq-tkn8auhEDRUcIWOguAdh8ta5c',
    appId: '1:123921055286:android:6331bd45b41579a6ee2297',
    messagingSenderId: '123921055286',
    projectId: 'daali-mobile-project-e19fb',
    storageBucket: 'daali-mobile-project-e19fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7kzZ9vzfta6F39MDlCIFtV2zE9fsHVN4',
    appId: '1:123921055286:ios:039eb0a06c913fc6ee2297',
    messagingSenderId: '123921055286',
    projectId: 'daali-mobile-project-e19fb',
    storageBucket: 'daali-mobile-project-e19fb.appspot.com',
    iosBundleId: 'com.example.tut1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7kzZ9vzfta6F39MDlCIFtV2zE9fsHVN4',
    appId: '1:123921055286:ios:aa5914e2759fe6bfee2297',
    messagingSenderId: '123921055286',
    projectId: 'daali-mobile-project-e19fb',
    storageBucket: 'daali-mobile-project-e19fb.appspot.com',
    iosBundleId: 'com.example.tut1.RunnerTests',
  );
}
